server:
  port: 8081

logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG

spring:
  security:
    oauth2:
      client:
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          linkedin:
            authorization-uri: https://www.linkedin.com/oauth/v2/authorization
            token-uri: https://www.linkedin.com/oauth/v2/accessToken
            user-info-uri: https://api.linkedin.com/v2/userinfo
        registration:
          linkedin:
            client-name: ${OAUTH2.LINKEDIN.CLIENT_NAME}
            redirect-uri: ${OAUTH2.LINKEDIN.REDIRECT_URI}
            authorization-grant-type: code
            token-grant-type-param: authorization_code
            client-id: ${OAUTH2.LINKEDIN.CLIENT_ID}
            client-secret: ${OAUTH2.LINKEDIN.CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
          google:
            client-name: ${OAUTH2.GOOGLE.CLIENT_NAME}
            redirect-uri: ${OAUTH2.GOOGLE.REDIRECT_URI}
            authorization-grant-type: code
            client-id: ${OAUTH2.GOOGLE.CLIENT_ID}
            scope:
              - https://www.googleapis.com/auth/userinfo.email
              - https://www.googleapis.com/auth/userinfo.profile
              - openid
            client-secret: ${OAUTH2.GOOGLE.CLIENT_SECRET}
            access_type: offline

  application:
    name: user-admin
    client-app-home-url: https://abdulsaasapp.com # Sample url, Replace this with the actual url of the client app.
  datasource:
    url: ${DATASOURCE.URL}
    driver-class-name: ${DATASOURCE.DRIVER.CLASS}
    username: ${DATASOURCE.USERNAME}                # Default H2 username
    password: ${DATASOURCE.PASSWORD}                # Default H2 password is empty

  h2:
    console:
      enabled: true             # Enables the H2 console at /h2-console
      path: /h2-console
  sql:
    init:
      platform: h2

  jpa:
    database-platform: ${JPA.DATABASE.PLATFORM}  # H2 dialect for JPA
    hibernate:
      ddl-auto: update             # Automatically creates and updates tables based on entities
    show-sql: true                 # Logs SQL statements for debugging (optional)